# Generated by Django 4.2.25 on 2025-10-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Priority', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=30, null=True)),
                ('SubmitDate', models.DateTimeField(auto_now_add=True)),
                ('DeadlineDate', models.DateTimeField(blank=True, null=True)),
                ('ResolvedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('UserType', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('PhoneNo', models.CharField(blank=True, max_length=10, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('LoginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=50, null=True)),
                ('Message', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(blank=True, max_length=100, null=True)),
                ('Vote', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.complaintstable')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(blank=True, max_length=30, null=True)),
                ('HeadName', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('LoginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.logintable')),
            ],
        ),
        migrations.AddField(
            model_name='complaintstable',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.departmentstable'),
        ),
        migrations.AddField(
            model_name='complaintstable',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.usertable'),
        ),
    ]
