# Generated by Django 4.2.25 on 2025-11-09 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='Vote',
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='DateSubmitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedbacktable',
            name='FeedbackText',
            field=models.TextField(default='No feedback provided'),
        ),
    ]
