# Generated by Django 4.2.25 on 2025-11-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0002_remove_feedbacktable_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='UserId',
        ),
        migrations.AddField(
            model_name='notification',
            name='Type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
