# Generated by Django 4.2.25 on 2025-11-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0003_remove_notification_userid_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='Replay',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
