# Generated by Django 4.2.25 on 2025-11-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0004_feedbacktable_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstable',
            name='Email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='Replay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
