# Generated by Django 4.2.25 on 2025-11-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0005_departmentstable_email_alter_feedbacktable_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='Address',
        ),
    ]
