# Generated by Django 4.2.25 on 2025-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0006_remove_usertable_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Email',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
