# Generated by Django 4.2.25 on 2025-12-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0007_alter_usertable_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintstable',
            name='Location',
        ),
        migrations.AddField(
            model_name='complaintstable',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaintstable',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
