# Generated by Django 4.2.25 on 2025-12-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0008_remove_complaintstable_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstable',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaintstable',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
