# Generated by Django 4.2.25 on 2025-12-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0009_alter_complaintstable_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintstable',
            name='DeadlineDate',
        ),
        migrations.RemoveField(
            model_name='complaintstable',
            name='ResolvedDate',
        ),
        migrations.CreateModel(
            name='AssignWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignedDate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(default='Assigned', max_length=30)),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.complaintstable')),
            ],
        ),
    ]
