# Generated by Django 4.2.25 on 2025-12-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0010_remove_complaintstable_deadlinedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Type',
        ),
        migrations.AddField(
            model_name='notification',
            name='Complaintid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cityApp.complaintstable'),
        ),
    ]
