# Generated by Django 4.2.25 on 2025-12-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0011_remove_notification_subject_remove_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Complaintid',
        ),
        migrations.AddField(
            model_name='notification',
            name='Assignid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cityApp.assignwork'),
        ),
    ]
