# Generated by Django 4.2.25 on 2025-12-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0012_remove_notification_complaintid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignwork',
            name='AssignedDate',
        ),
        migrations.AddField(
            model_name='assignwork',
            name='EndingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignwork',
            name='Status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
