# Generated by Django 4.2.25 on 2025-12-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0013_remove_assignwork_assigneddate_assignwork_endingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintstable',
            name='EndingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
