# Generated by Django 4.2.25 on 2025-12-29 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0014_complaintstable_endingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('Remark', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.complaintstable')),
            ],
        ),
    ]
