# Generated by Django 4.2.25 on 2025-12-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0015_timelinetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinetable',
            name='EndingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
