# Generated by Django 4.2.25 on 2025-12-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0016_timelinetable_endingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintstable',
            name='is_anonymous',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
