# Generated by Django 4.2.25 on 2025-12-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0017_complaintstable_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstable',
            name='Status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
