# Generated by Django 4.2.25 on 2025-12-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0018_alter_complaintstable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstable',
            name='DepartmentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cityApp.departmentstable'),
        ),
    ]
