# Generated by Django 4.2.25 on 2025-12-31 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0019_alter_complaintstable_departmentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Points', models.IntegerField()),
                ('CreatedDate', models.DateTimeField()),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.complaintstable')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentText', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cityApp.complaintstable')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikedAt', models.DateTimeField(auto_now_add=True)),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cityApp.complaintstable')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.usertable')),
            ],
            options={
                'unique_together': {('ComplaintId', 'UserId')},
            },
        ),
    ]
