# Generated by Django 4.2.25 on 2026-01-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0020_pointstable_complaintcomment_complaintlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Badge', models.CharField(max_length=20)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField()),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityApp.complaintstable')),
            ],
        ),
    ]
