# Generated by Django 4.2.25 on 2026-01-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0021_badgetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgetable',
            name='point',
        ),
        migrations.RemoveField(
            model_name='pointstable',
            name='UserId',
        ),
    ]
