# Generated by Django 4.2.25 on 2026-01-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0022_remove_badgetable_point_remove_pointstable_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetable',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pointstable',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
