# Generated by Django 4.2.25 on 2026-01-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0023_alter_badgetable_createddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='ComplaintId',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Assignid',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Message',
        ),
        migrations.AddField(
            model_name='notification',
            name='ComplaintsId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cityApp.complaintstable'),
        ),
    ]
