# Generated by Django 4.2.25 on 2026-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0024_remove_feedbacktable_complaintid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertable',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
    ]
