# Generated by Django 4.2.25 on 2026-01-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0026_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
