# Generated by Django 4.2.25 on 2026-01-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0027_usertable_address_usertable_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
