# Generated by Django 4.2.25 on 2026-01-25 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0028_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ComplaintsId',
        ),
        migrations.AddField(
            model_name='notification',
            name='TimeLineId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cityApp.timelinetable'),
        ),
    ]
