# Generated by Django 4.2.25 on 2026-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityApp', '0030_alter_complaintstable_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstable',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
